name: Build Image using Dockerfile
on: [push]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: chenliu90/jarvis-bi
        tags: v0.1 ${{ github.event.pull_request.number }} ${{ github.sha }}
        dockerfiles: |
          ./Dockerfile
